name: search/kcolor/5
seed: 1

log_level: info
report_interval: 10
eval_interval: 50
save_interval: 50

# pretraining section
data_shuffle: True

latent_size: 16
pretrain_vgae:
  num_epochs: 20
  out_name: vgae_mixed_all_v1.pth
  batch_size: 16

data_path: data/mixed
train_sets:
  - name: '1comp'
    samples: 8000
    max_tries: 5
    max_flips: 200
    iterations: 10000

eval_set:
  name: '2comp'
  samples: 2400
  max_tries: 25
  max_flips: 300

mlp_arch:
  hidden_sizes: [32]
  activation: ReLU

model_path: results/

gnn_hidden_size: 32
gnn_iter: 2
readout_hidden_size: 64

cycles: 1
optimizer: RMSprop
lr: 0.0005
lr_milestones: [200, 500, 1000, 5000]
lr_decay: 0.5

method: reinforce_augmented
discount: 0.25
walk_prob: 0.5
